version: '3'

services:
  database:
    image: postgres
    container_name: tasks-microservice-register-database
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRESQL_USERNAME=${DB_USERNAME}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_DATABASE=${DB_DATABASE}
    volumes:
      - pgdata:/data/postgres
